// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dMvn
arma::mat dMvn(arma::mat x, arma::rowvec mean, arma::mat sigma, bool log);
RcppExport SEXP _bmbclust_dMvn(SEXP xSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dMvn(x, mean, sigma, log));
    return rcpp_result_gen;
END_RCPP
}
// dMvn_multi
arma::mat dMvn_multi(arma::mat x_tmp, arma::rowvec mean, arma::mat sigma, int K, bool log);
RcppExport SEXP _bmbclust_dMvn_multi(SEXP x_tmpSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP KSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x_tmp(x_tmpSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dMvn_multi(x_tmp, mean, sigma, K, log));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bmbclust_dMvn", (DL_FUNC) &_bmbclust_dMvn, 4},
    {"_bmbclust_dMvn_multi", (DL_FUNC) &_bmbclust_dMvn_multi, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_bmbclust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
