# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dMvn <- function(x, mean, sigma, log = FALSE) {
    .Call(`_bmbclust_dMvn`, x, mean, sigma, log)
}

dMvn_multi <- function(x_tmp, mean, sigma, K, log = FALSE) {
    .Call(`_bmbclust_dMvn_multi`, x_tmp, mean, sigma, K, log)
}

